### ISSUE TITLE
Interface Keypad to Beaglebone 

### ISSUE THREAD

**Issue by srikanthpendem** [srikanthpendem/capstoneproject#14]

**Comment by Devanggajjar** [comment]
### How to connect the buttons with BBB

1. ### Firstly we need to connect the buttons with the BBB in order to read the output from the GPIO pins.

2. ### Connection with the BBB will only read the “HIGH” and “LOW” readings from the controller.

3.  ### All the green GPIO we can use for connections.
 
********************************************************************************************************************************************************************************************************************************************************************************

![beaglebone-black-pinout](https://user-images.githubusercontent.com/55203414/89670400-26336400-d8af-11ea-8009-a456818b861c.jpg)

********************************************************************************************************************************************************************************************************************************************************************************

4. ### We are using P8 header 12th pin and 14th pin.

5. ### Also we have to make sure that we use the pull-down resistor of 1KOhm or greater in order to connect the buttons otherwise it will damage the controller.

********************************************************************************************************************************************************************************************************************************************************************************

![116592333_931086174064150_3970050885636507013_n](https://user-images.githubusercontent.com/55203414/89670764-ba053000-d8af-11ea-9342-c26f764f218e.jpg)

*******************************************************************************************************************************************************************************************************************************************************************************

**Comment by mikeshams** [comment]
1. Why did you choose the buttons instead of the keypad?
2. What issues did you face when connecting the buttons to the BBB in terms of hardware and software?
3. How did you solve those issues?

**Comment by Devanggajjar** [comment]
1.  It is less complex. Easy to remember a binary password(b1b2b2b1b1b2b2), the Button interface will fulfill our requirement.
2. The GPIO port continuously get input, that may affect output read values, it's won't be digital. 
3. Proper sleep should be given or use an ADC IC.
